# Generated by Django 3.0.8 on 2020-08-07 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
                ('precio', models.FloatField(default=0)),
                ('stock', models.FloatField(default=0)),
                ('iva', models.BooleanField(default=True)),
                ('prueba', models.BooleanField(default=True)),
                ('creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creacion')),
                ('modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha Modificacion')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['-creacion'],
            },
        ),
    ]
