# Generated by Django 3.0.8 on 2020-08-07 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Facturacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruc', models.CharField(max_length=13)),
                ('nombre', models.CharField(max_length=300)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creacion')),
                ('modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha Modificacion')),
                ('producto', models.ManyToManyField(to='Facturacion.Producto')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['-creacion'],
            },
        ),
    ]
