# Generated by Django 3.0.8 on 2020-08-07 20:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Facturacion', '0002_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('precio', models.FloatField()),
                ('stock', models.FloatField()),
                ('iva', models.BooleanField(default=True)),
                ('fecha', models.DateTimeField(default=datetime.datetime(2020, 8, 7, 15, 54, 5, 216630))),
                ('creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creacion')),
                ('modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha Modificacion')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Facturacion.Producto')),
            ],
            options={
                'verbose_name': 'Entrada',
                'verbose_name_plural': 'Entradas',
                'ordering': ['-creacion'],
            },
        ),
    ]
