# Generated by Django 3.0.8 on 2020-08-07 21:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Facturacion', '0003_entrada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 7, 16, 49, 50, 24421)),
        ),
        migrations.CreateModel(
            name='EntradaC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruc', models.TextField()),
                ('nombre', models.TextField()),
                ('direccion', models.TextField()),
                ('producto', models.TextField()),
                ('creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creacion')),
                ('modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha Modificacion')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Facturacion.Cliente')),
            ],
            options={
                'verbose_name': 'Entrada',
                'verbose_name_plural': 'Entradas',
                'ordering': ['-creacion'],
            },
        ),
    ]
