# Generated by Django 3.0.8 on 2020-08-07 22:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Facturacion', '0004_auto_20200807_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 7, 17, 6, 55, 567027)),
        ),
        migrations.RemoveField(
            model_name='entradac',
            name='producto',
        ),
        migrations.AddField(
            model_name='entradac',
            name='producto',
            field=models.ManyToManyField(to='Facturacion.Producto'),
        ),
    ]
