# Generated by Django 3.0.8 on 2020-08-07 22:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Facturacion', '0005_auto_20200807_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='prueba',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='entrada',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 7, 17, 21, 18, 436289)),
        ),
        migrations.DeleteModel(
            name='EntradaC',
        ),
    ]
