# Generated by Django 3.0.8 on 2020-08-07 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Facturacion', '0006_auto_20200807_1721'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Entrada',
        ),
    ]
