# Generated by Django 3.0.8 on 2020-08-08 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Facturacion', '0008_factura'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Factura',
        ),
    ]
